return {
  'folke/which-key.nvim',
  -- event = 'VimEnter', -- Sets the loading event to 'VimEnter'
  event = 'VeryLazy', -- Sets the loading event to 'VimEnter'
  opts = {
    icons = {
      -- set icon mappings to true if you have a Nerd Font
      mappings = vim.g.have_nerd_font,
      -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
      -- default which-key.nvim defined Nerd Font icons, otherwise define a string table
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    -- Document existing key chains
    spec = {
      { '<leader>b', group = 'Buffers' },
      { '<leader>и', group = 'Buffers' },
      { '<leader>c', group = 'Code', mode = { 'n', 'x' } },
      { '<leader>с', group = 'Code', mode = { 'n', 'x' } },
      { '<leader>d', group = 'Document', mode = { 'n', 'x' } },
      { '<leader>dl', group = 'Lines', mode = { 'n', 'x' } },
      -- { '<leader>r', group = '[R]ename' },
      { '<leader>s', group = 'Search' },
      { '<leader>ы', group = 'Search' },
      { '<leader>f', group = 'Find' },
      { '<leader>а', group = 'Find' },
      { '<leader>t', group = 'Toggle' },
      { '<leader>е', group = 'Toggle' },
      { '<leader>w', group = 'Windows' },
      { '<leader>ц', group = 'Windows' },
      -- { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>g', group = 'Git', mode = { 'n', 'v' } },
      { '<leader>п', group = 'Git', mode = { 'n', 'v' } },
      { '<leader>gh', group = 'Git hunks', mode = { 'n', 'v' } },
      { '<leader>m', group = 'Obsidian' },
      { '<leader>ь', group = 'Obsidian' },
      { '<leader>q', group = 'Sessions', mode = { 'n', 'v' } },
      { '<leader>й', group = 'Sessions', mode = { 'n', 'v' } },
      { '<leader>ml', group = 'Links' },
      { '<leader>ms', group = 'Search' },
      { '<leader>mc', group = 'Create' },
    },
  },
}
